version: "2"
linters:
  default: none
  enable:
    # - bodyclose
    - dogsled
    # - errcheck
    # - funlen
    # - gochecknoinits
    # - goconst
    # - gocritic
    # - gocyclo
    # - gosec
    # - govet
    - ineffassign
    # - lll
    - misspell
    - nakedret
    # - staticcheck
    - unconvert
    # - unparam
    # - unused
    - whitespace
  settings:
    funlen:
      lines: 200 # TODO: make it 120
      statements: 60
    goconst:
      min-len: 2
      min-occurrences: 2
    gocritic:
      disabled-checks:
        - whyNoLint
        - paramTypeCombine
        - sloppyReassign
      enabled-tags:
        - diagnostic
        - performance
        - style
        - experimental
      settings:
        hugeParam:
          sizeThreshold: 256
        rangeValCopy:
          sizeThreshold: 256
    gocyclo:
      min-complexity: 25
    lll:
      line-length: 200 # TODO: make it 140 and fix linter errors
    misspell:
      locale: US
  exclusions:
    generated: lax
    rules:
      - linters:
          - dogsled
          - funlen
          - goconst
          - gocritic
          - gocyclo
          - gosec
          - govet
          - ineffassign
          - lll
          - staticcheck
          - unparam
          - unused
          - staticcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    # - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/hypernetix/hyperspot/
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
